docs/installing/api.rst: Include example for docker.servers
This shows folks how to configure at least one Docker server so that tsr
doesn't fail with:

    Error: You should configure the docker servers.