iaas/cloudstack: check only the two first calls in tests
Fixing the intermitence of another test. Instead of checking all the
calls, we can check just the two first calls, because there's an async
call to the deleteVirtualMachine task.

That's why sometimes we see the following error failure:

----------------------------------------------------------------------
FAIL: iaas_test.go:75: cloudstackSuite.TestCreateMachineAsyncFailure

iaas_test.go:102:
    c.Assert(calls, check.DeepEquals, []string{"deployVirtualMachine", "queryAsyncJobResult"})
... obtained []string = []string{"deployVirtualMachine", "queryAsyncJobResult", "listVolumes"}
... expected []string = []string{"deployVirtualMachine", "queryAsyncJobResult"}

OOPS: 10 passed, 1 FAILED
--- FAIL: Test (38.61s)
FAIL
FAIL	github.com/tsuru/tsuru/iaas/cloudstack	38.641s